name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  quality-and-tests:
    name: PHP ${{ matrix.php }} SM ${{ matrix.sm }} - lint, phpcs, psalm, phpunit
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php == '8.5' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4', '8.5' ]
        deps: [lowest, highest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2
          extensions: json

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install (lockfile)
        if: matrix.deps == 'highest'
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Update to lowest allowed
        if: matrix.deps == 'lowest'
        run: composer update --no-interaction --prefer-lowest --prefer-stable --with-all-dependencies

      - name: PHP Lint
        run: |
          find src tests -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l

      - name: Run PHPCS
        run: vendor/bin/phpcs -q

      - name: Run Psalm
        run: vendor/bin/psalm --output-format=github --no-cache

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --colors=always
